# Generated by Django 5.0.8 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (32x32 or 64x64 pixels)', null=True, upload_to='favicon/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#f59e0b', help_text='Primary theme color (hex code, e.g., #f59e0b)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0b1220', help_text='Secondary/background color (hex code, e.g., #0b1220)', max_length=7),
        ),
    ]